name: Deploy to Flex

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: environment
        description: "Environment to use for deployment"

jobs:
  deploy-serverless:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    env:
      ENVIRONMENT: ${{ github.event.inputs.environment }}
      TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
      TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
      TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}
      LINE_STUDIO_FLOW_SID: ${{ secrets.LINE_STUDIO_FLOW_SID }}
      LINE_CHANNEL_ID: ${{ secrets.LINE_CHANNEL_ID }}
      LINE_CHANNEL_SECRET: ${{ secrets.LINE_CHANNEL_SECRET }}
      LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
      VIBER_STUDIO_FLOW_SID: ${{ secrets.VIBER_STUDIO_FLOW_SID }}
      VIBER_AUTH_TOKEN: ${{ secrets.VIBER_AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install NPM packages
        id: install-npm
        run: |
          npm install
          npm run install-serverless-plugin
          npm run setup-environment $ENVIRONMENT
          npm run deploy-env
